baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Namit Gupta Website'
theme = "PaperMod"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "about/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "projects/"
  weight = 2

baseURL = "https://Namit-G.github.io/"
canonifyURLs = true
relativeURLs = false
