baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "about/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "projects/"
  weight = 2